### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Victor725** [mapleafgo/clash-for-flutter#13]
您好 请问为什么添加订阅链接后，还是显示没有节点？ 订阅链接在windows端用着是正常的
我下载的是https://github.com/mapleafgo/clash-for-flutter/releases/download/v0.0.7-alpha/clashforflutter_0.0.7_amd64.deb  这个release包，系统是ubuntu21.04，已经手动更新了订阅链接

**Comment by mapleafgo** [comment]
未开启代理的情况下，是不会显示节点的

**Comment by Victor725** [comment]
我已经在软件内开启代理了  系统设置里也把代理设成自动了
![image](https://user-images.githubusercontent.com/55656122/127081022-405b13b6-c342-473a-9ec7-982552f8a3c8.png)

**Comment by mapleafgo** [comment]
你可以检查下更新的订阅文件，以确认订阅文件确实无误。订阅文件Linux下应该在`.local/clash_for_flutter/profiles`这个文件夹下，我如果不是可以用`find ~ -name "cfm.json"`确认下配置文件路径

**Comment by sky5454** [comment]
> 你可以检查下更新的订阅文件，以确认订阅文件确实无误。订阅文件Linux下应该在`.local/clash_for_flutter/profiles`这个文件夹下，我如果不是可以用`find ~ -name "cfm.json"`确认下配置文件路径

其实问题是

```bash
~/soft> ./Clash_For_Flutter-0.0.7-x86_64.AppImage 
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":92.53889943074003,"monitorWidthMm":527,"monitorWidthSc":1920,"mscpi":92.53889943074003,"pixelRatio":0.5783681214421252,"ppsc":1,"windowWidthPx":900,"windowWidthSc":900}

(clash_for_flutter:18018): libappindicator-CRITICAL **: 20:26:31.917: app_indicator_set_label: assertion 'IS_APP_INDICATOR (self)' failed
go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'
INFO[0003] Start initial compatible provider :clapper:Netflix 
INFO[0003] Start initial compatible provider :clapper:哔哩哔哩 
INFO[0003] Start initial compatible provider :anchor:其他流量 
INFO[0003] Start initial compatible provider :rocket:直接连接 
INFO[0003] Start initial compatible provider :beginner:国外流量 
INFO[0003] Start initial compatible provider :apple:苹果服务 
INFO[0003] Start initial compatible provider :clapper:Youtube 
INFO[0003] Start initial compatible provider :clapper:国外媒体 
INFO[0003] Start initial compatible provider :airplane:Telegram 
INFO[0003] Mixed(http+socks5) proxy listening at: 127.0.0.1:7890 
INFO[0003] RESTful API listening at: 127.0.0.1:9090     
go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'ProxieType'
#0      _data.<anonymous closure>.<anonymous closure> (package:clash_for_flutter/main.mapper.g.dart:51)
#1      Function._apply (dart:core-patch/function_patch.dart:11)
#2      Function.apply (dart:core-patch/function_patch.dart:34)
#3      ClassMirrorBase.newInstance (package:reflectable/src/reflectable_builder_based.dart:669)
#4      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:929)
#5      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:41)
#6      JsonMapper.fromMap (package:dart_json_mapper/src/mapper.dart:66)
#7      ProviderProxiesConverter.fromJSON.<anonymous closure> (package:clash_for_flutter/app/bean/provider_bean.dart:33)
#8      MappedIterable.elementAt (dart:_internal/iterable.dart:372)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:341)
#10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#12     new List.of (dart:core-patch/array_patch.dart:50)
#13     SetMixin.toList (dart:collection/set.dart:118)
#14     ProviderProxiesConverter.fromJSON (package:clash_for_flutter/app/bean/provider_bean.dart:35)
#15     JsonMapper._getConvertedValue (package:dart_json_mapper/src/mapper.dart:415)
#16     JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:886)
#17     JsonMapper._enumerateConstructorParameters.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:631)
#18     _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
#19     JsonMapper._enumerateConstructorParameters (package:dart_json_mapper/src/mapper.dart:597)
#20     JsonMapper._getNamedArguments (package:dart_json_mapper/src/mapper.dart:689)
#21     JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:922)
#22     JsonMapper._configureConverter.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:740)
#23     MapConverter.fromJSON.<anonymous closure> (package:dart_json_mapper/src/model/converters.dart:391)
#24     MapMixin.map (dart:collection/maps.dart:170)
#25     MapConverter.fromJSON (package:dart_json_mapper/src/model/converters.dart:389)
#26     JsonMapper._getConvertedValue (package:dart_json_mapper/src/mapper.dart:415)
#27     JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:886)
#28     JsonMapper._enumerateConstructorParameters.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:631)
#29     _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
#30     JsonMapper._enumerateConstructorParameters (package:dart_json_mapper/src/mapper.dart:597)
#31     JsonMapper._getNamedArguments (package:dart_json_mapper/src/mapper.dart:689)
#32     JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:922)
#33     JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:41)
#34     JsonMapper.fromMap (package:dart_json_mapper/src/mapper.dart:66)
#35     Request.getProxyProviders (package:clash_for_flutter/app/source/request.dart:45)
<asynchronous suspension>
#36     ProxysController.getProviders (package:clash_for_flutter/app/pages/proxys/proxys_controller.dart:46)
<asynchronous suspension>
#37     ProxysController.initState (package:clash_for_flutter/app/pages/proxys/proxys_controller.dart:18)
<asynchronous suspension>

go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'
^C

```


我的系统： Opensuse Tumbleweed

**Comment by mapleafgo** [comment]
@sky5454 你这个问题很好定位，是获取的列表解析出问题了，代理是开启了的。你应该跟他不是一个情况，你这种应该win也会报错

**Comment by sky5454** [comment]
> @sky5454 你这个问题很好定位，是获取的列表解析出问题了，代理是开启了的。你应该跟他不是一个情况，你这种应该win也会报错

其他软件都可以，包括windows版cfw

**Comment by mapleafgo** [comment]
@sky5454 我是说我这软件☺️应该都会报这个错

**Comment by mapleafgo** [comment]
@sky5454 你这个问题修复了，代理类型不在枚举中，取消了转枚举，采用直接显示。
